### ISSUE TITLE
Travis is disabled.

### ISSUE THREAD

**Issue by epage** [booyaa/booyaa.github.io#4]
From https://github.com/booyaa/booyaa.github.io/commit/8f6f1952bc0edc782a17dc665b73be93d785d00d#diff-ff68cbddaf9893cd0e69b3d3b93d78e3 it looks like you are having problems with deployment

See https://github.com/cobalt-org/cobalt.rs/pull/333 for a possible fix.

**Comment by booyaa** [comment]
thanks for that, travis is looking happier!
